version: '3.8'

services:
  vehicle-detection:
    build: .
    container_name: vehicle-detection-production
    restart: unless-stopped
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
      - /dev:/dev
      - /sys:/sys:ro
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      - /usr/lib/librknnrt.so:/usr/lib/librknnrt.so:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/mali0:/dev/mali0
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
    environment:
      - USE_RKNN=1
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:/usr/lib
      - OPENCV_LOG_LEVEL=ERROR
    network_mode: "host" 